name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        # os: [windows-2019]
        # os: [ubuntu-20.04, windows-2019, macOS-10.15]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
              
        run: python -m pip install cibuildwheel twine virtualenv numpy cython

      - name: Build wheels
        env:
            CIBW_BUILD: 'cp39-* cp310-* cp311-*'
            CIBW_SKIP: 'pp* *686* *-musllinux_*'
            CIBW_ARCHS_MACOS: 'x86_64 arm64'
            CIBW_BEFORE_ALL_LINUX: yum install -y alsa-lib-devel jack-audio-connection-kit-devel
        run: |
            # python setup.py build_ext
            python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
      - name: Upload wheels
        env:
            TWINE_USERNAME: Eduardo.Moguillansky
            TWINE_PASSWORD: ${{ secrets.pypipass }}
        run: |
            echo $TWINE_USERNAME
            echo $TWINE_PASSWORD
            twine upload --skip-existing wheelhouse/*.whl
        continue-on-error: true
